spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database
    username: your_user
    password: your_password

  rabbitmq:
    host: localhost
    port: 5672
    username: YOUR_USERNAME
    password: YOUR_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

weather:
  api:
    key: YOUR_API_KEY_HERE

jwt:
  secret: YOUR_JWT_SECRET_HERE

ai:
  base-url: https://openrouter.ai/api/v1
  api-key: YOUR_API_KEY
  model: google/gemma-3-27b-it:free